version: '3.7'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - cotacao-net

  api:
    image: node:18-alpine
    depends_on:
      - mongo
    entrypoint: sh -c 'yarn && yarn run dev'
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    restart: "on-failure"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - cotacao-net

networks: 
  cotacao-net:
    driver: bridge
